# Generated by Django 5.0.1 on 2024-02-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_crear_cuenta_productos_delete_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crear_cuenta',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
